name: mpn_lookup_flutter
dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  cupertino_icons: ^1.0.8
  husky: ^0.1.7
  lint_staged: ^0.5.1
  dart_style: ^3.0.1
  url_launcher: ^6.3.1
  commitlint_cli: ^0.8.1
  provider: ^6.1.2
  go_router: ^14.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.8
  integration_test:
    sdk: flutter

lint_staged:
  'lib/**.dart': dart format -l 120 && dart analyze --fatal-infos --fatal-warnings .
