#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running pre-commit hook"
dart format . -l 120 --set-exit-if-changed
dart analyze --fatal-infos --fatal-warnings .
dart run lint_staged
flutter test
echo "Running pre-commit hook 2"
