
name: CI

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze Dart code
        run: dart analyze

      - name: Run Flutter tests
        run: flutter test
